### ISSUE TITLE
Crash on Android in release.

### ISSUE THREAD

**Issue by shpy2001** [decodedhealth/flutter_zoom_plugin#14]
I has tested on 10 Android devices. All of them crash when run release but ok on debug mode !

Android Logcat show this:

2020-03-21 16:30:57.324 21419-21419/? E/ZMBuildConfig: parse build target failed. value=TARGET_ZOOM
    java.lang.NoSuchFieldException: TARGET_ZOOM
        at java.lang.Class.getField(Class.java:1549)
        at g.a.b.n.<clinit>(ZMBuildConfig.java:4)
        at com.zipow.cmmlib.AppContext.<clinit>(AppContext.java:5)
        at com.zipow.cmmlib.AppContext.a(AppContext.java:1)
        at us.zoom.sdk.t.a(ZoomSDK.java:16)
        at c.c.a.f.a(ZoomView.java:11)
        at c.c.a.f.onMethodCall(ZoomView.java:5)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:2)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:5)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:2)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java)
        at android.os.Looper.loop(Looper.java)
        at android.app.ActivityThread.main(ActivityThread.java)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)

**Comment by shpy2001** [comment]
I found it crash by proguard. So, i added these line in proguard file and it work now.

-keep class us.zoom.** { *; }
-keep class us.zipow.** { *; }
-keep class com.zipow.** { *; }
-keep class org.webrtc.** { *; }


-dontwarn us.zoom.**
-dontwarn com.zipow.**

**Comment by cacianokroth** [comment]
To me it`s don`t working @shpy2001  :(

**Comment by cacianokroth** [comment]
correctly guards: 
```
-keep class us.zoom.** { *; }
-keep class us.zipow.** { *; }
-keep class com.zipow.** { *; }
-keep class org.webrtc.** { *; }

-dontwarn us.zoom.**
-dontwarn com.zipow.**
```

**Comment by shpy2001** [comment]
> correctly guards:
> 
> ```
> -keep class us.zoom.** { *; }
> -keep class us.zipow.** { *; }
> -keep class com.zipow.** { *; }
> -keep class org.webrtc.** { *; }
> 
> -dontwarn us.zoom.**
> -dontwarn com.zipow.**
> ```

Sorry for my typing mistake.
