### ISSUE TITLE
Error on android emulator 

### ISSUE THREAD

**Issue by shaharsol** [decodedhealth/flutter_zoom_plugin#4]
Can you figure out what's wrong? I'm using an emulator with API version 29, maybe that's too high? 

```
E/flutter ( 4747): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/FragmentActivity;
E/flutter ( 4747): 	at com.zipow.videobox.ptapp.PTUI.getInstance(Unknown Source:0)
E/flutter ( 4747): 	at us.zoom.sdk.ZoomSDK.<init>(ZoomSDK.java:150)
E/flutter ( 4747): 	at us.zoom.sdk.ZoomSDK.getInstance(ZoomSDK.java:162)
E/flutter ( 4747): 	at com.decodedhealth.flutter_zoom_plugin.ZoomView.init(ZoomView.java:71)
E/flutter ( 4747): 	at com.decodedhealth.flutter_zoom_plugin.ZoomView.onMethodCall(ZoomView.java:53)
E/flutter ( 4747): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/flutter ( 4747): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/flutter ( 4747): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/flutter ( 4747): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 4747): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter ( 4747): 	at android.os.Looper.loop(Looper.java:174)
E/flutter ( 4747): 	at android.app.ActivityThread.main(ActivityThread.java:7343)
E/flutter ( 4747): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 4747): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/flutter ( 4747): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:933)
E/flutter ( 4747): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.FragmentActivity" on path: DexPathList[[zip file "/data/app/com.sanghaline-wGb6-s9fAAD1NThl4xNR_g==/base.apk"],nativeLibraryDirectories=[/data/app/com.sanghaline-wGb6-s9fAAD1NThl4xNR_g==/lib/x86, /data/app/com.sanghaline-wGb6-s9fAAD1NThl4xNR_g==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
E/flutter ( 4747): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
E/flutter ( 4747): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/flutter ( 4747): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/flutter ( 4747): 	... 15 more
E/flutter ( 4747): 
```

**Comment by kevinbayes** [comment]
I need to update the library zoom sdk.

**Comment by kevinbayes** [comment]
@shaharsol try the latest commit and let me know.

**Comment by shaharsol** [comment]
@kevinbayes now it works when i run your sample app (should the video looks like this?):

<img width="365" alt="Screen Shot 2019-11-05 at 11 50 24" src="https://user-images.githubusercontent.com/672778/68200210-14432e80-ffc8-11e9-9c15-5653b2dc10cb.png">

However, in *my* app, that uses the plugin as a dependency in this manner:

```
  flutter_zoom_plugin:
    git:
      url: git://github.com/decodedhealth/flutter_zoom_plugin.git
```

I still get the same exception, though I'm pretty sure I've rebuilt it, coz since your upgrade I had to follow on and change the `compileSdkVersion` and the `targetSdkVersion` to 29...

```
W/Gralloc3(16320): allocator 3.x is not supported
I/flutter (16320): Created the view
D/EGL_emulation(16320): eglMakeCurrent: 0x8f01a0c0: ver 3 0 (tinfo 0x8f00f690)
E/BluetoothAdapter(16320): Bluetooth binder is null
I/chatty  (16320): uid=10132(com.sanghaline) identical 1 line
E/BluetoothAdapter(16320): Bluetooth binder is null
E/flutter (16320): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/FragmentActivity;
E/flutter (16320): 	at com.zipow.videobox.ptapp.PTUI.getInstance(Unknown Source:0)
E/flutter (16320): 	at us.zoom.sdk.ZoomSDK.<init>(ZoomSDK.java:154)
E/flutter (16320): 	at us.zoom.sdk.ZoomSDK.getInstance(ZoomSDK.java:167)
E/flutter (16320): 	at com.decodedhealth.flutter_zoom_plugin.ZoomView.init(ZoomView.java:71)
E/flutter (16320): 	at com.decodedhealth.flutter_zoom_plugin.ZoomView.onMethodCall(ZoomView.java:53)
E/flutter (16320): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/flutter (16320): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/flutter (16320): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/flutter (16320): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (16320): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter (16320): 	at android.os.Looper.loop(Looper.java:174)
E/flutter (16320): 	at android.app.ActivityThread.main(ActivityThread.java:7343)
E/flutter (16320): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (16320): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/flutter (16320): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:933)
E/flutter (16320): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.FragmentActivity" on path: DexPathList[[zip file "/data/app/com.sanghaline-Q5-ENKkCFB_g042WljvB2Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.sanghaline-Q5-ENKkCFB_g042WljvB2Q==/lib/x86, /data/app/com.sanghaline-Q5-ENKkCFB_g042WljvB2Q==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
E/flutter (16320): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
E/flutter (16320): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/flutter (16320): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/flutter (16320): 	... 15 more

```

**Comment by kevinbayes** [comment]
@shaharsol yes that is the correct view for the emulator using the camera. You should test on device to get a feel of what it would look like on a real phone.

One question has your app been upgraded to androidx?

**Comment by shaharsol** [comment]
@kevinbayes 

Added those lines to `gradle.properties` and the `targetSdk` is 29 so AFAIK it's enough to migrate it to androidx.

Getting the same error message, only this time it's the adnroidx class (`Landroidx/fragment/app/FragmentActivity`)that it's DEF isnn't found:

```
E/flutter (19060): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/fragment/app/FragmentActivity;
E/flutter (19060): 	at com.zipow.videobox.ptapp.PTUI.getInstance(Unknown Source:0)
E/flutter (19060): 	at us.zoom.sdk.ZoomSDK.<init>(ZoomSDK.java:154)
E/flutter (19060): 	at us.zoom.sdk.ZoomSDK.getInstance(ZoomSDK.java:167)
E/flutter (19060): 	at com.decodedhealth.flutter_zoom_plugin.ZoomView.init(ZoomView.java:71)
E/flutter (19060): 	at com.decodedhealth.flutter_zoom_plugin.ZoomView.onMethodCall(ZoomView.java:53)
E/flutter (19060): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/flutter (19060): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/flutter (19060): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/flutter (19060): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (19060): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter (19060): 	at android.os.Looper.loop(Looper.java:174)
E/flutter (19060): 	at android.app.ActivityThread.main(ActivityThread.java:7343)
E/flutter (19060): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (19060): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/flutter (19060): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:933)
E/flutter (19060): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.fragment.app.FragmentActivity" on path: DexPathList[[zip file "/data/app/com.sanghaline-UYFuT8XCc1DgLBd64LPl5Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.sanghaline-UYFuT8XCc1DgLBd64LPl5Q==/lib/x86, /data/app/com.sanghaline-UYFuT8XCc1DgLBd64LPl5Q==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
E/flutter (19060): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
E/flutter (19060): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/flutter (19060): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/flutter (19060): 	... 15 more
```

**Comment by kevinbayes** [comment]
@shaharsol can you create a repository with your setup that simulates the error? Then I can help out on fixing it.

**Comment by shaharsol** [comment]
@kevinbayes added you as collaborator, invite is here https://github.com/shaharsol/sanghaline-flutter/invitations
To reproduce:

1. sign in with username kevin@gnift.com, password 123456
2. navigate to instructors
3. click on the first one (Vidad)
4. navigate to Calendar
5. click the first item, this should start the zoom session

Thanks!

**Comment by kevinbayes** [comment]
Moved this thread to your project.
